require('dotenv').config();

const {
  VERSION = '1.0.0',
  NODE_ENV = 'development',
  PORT = '3333',

  DB_CLIENT_DEV,
  DB_HOST_DEV,
  DB_PORT_DEV,
  DB_USER_DEV,
  DB_PASSWORD_DEV,
  DB_DATABASE_DEV,

  DB_CLIENT_TEST,
  DB_FILENAME_TEST,

  DB_CLIENT,
  DB_HOST,
  DB_PORT,
  DB_USER,
  DB_PASSWORD,
  DB_DATABASE,

  HOST_QUEUE = 'localhost',
  ENABLED_QUEUE = false,
  EXCHANGE_NAME_QUEUE = 'order-exchange',
  NAME_QUEUE = 'order-queue'
} = process.env;

module.exports = {
  VERSION,
  NODE_ENV,
  PORT,
  
  DB_CLIENT_DEV,
  DB_HOST_DEV,
  DB_PORT_DEV,
  DB_USER_DEV,
  DB_PASSWORD_DEV,
  DB_DATABASE_DEV,

  DB_CLIENT_TEST,
  DB_FILENAME_TEST,

  DB_CLIENT,
  DB_HOST,
  DB_PORT,
  DB_USER,
  DB_PASSWORD,
  DB_DATABASE,

  HOST_QUEUE,
  ENABLED_QUEUE: JSON.parse(ENABLED_QUEUE),
  EXCHANGE_NAME_QUEUE,
  NAME_QUEUE
};